export { default as Home } from './home';
export { default as Login } from './login';
export { default as Register } from './register';
export { default as PageNotFound } from './A404';
export { default as PreviewPage } from './preview';
export { default as Account } from './account';
export { default as ResponsesPage } from './responses';
export { default as ResponsePage } from './response';
export { default as ForgotPassword } from './forgot_password';
export { default as ResetPassword } from './reset_password';
export { default as FormPage } from './form'
